src/Mcamara/LaravelLocalization/LaravelLocalizationServiceProvider.php

I noticed that if you want to use this package with another package that redefines the router (like [Dingo/api](https://github.com/dingo/api)), using the facade to define the filters does not work.

Use the router from the IOC container

---

src/Mcamara/LaravelLocalization/LaravelLocalization.php
tests/LocalizerTests.php

Warning when performing a parse_url($url) on a url without a trailing slash.
Eg: http://www.google.fr

Fix URL without trailing slash

---

README.md

Not sure if this is exactly the way to do it.  I found the "session" section kind of a weird add-on.  It seems to me that the new session middleware is required for expected behavior, so maybe it belongs along with the basic install instructions.

Session middleware as part of main install

---

src/Mcamara/LaravelLocalization/LaravelLocalization.php

Routes are not translated properly if the $url passed to getLocalizedURL is NULL because the if ( empty( $url ) ) check doesn't happen until after findTranslatedRouteByUrl().  This edit simply moves the if ( empty( $url ) ) logic above.

Fix broken translated routes

---

src/Mcamara/LaravelLocalization/LanguageNegotiator.php

if HTTP_ACCEPT_LANGUAGE is `*`, array_shift returns the full array instead of the language key. This results in an error:
```
production.ERROR: exception 'ErrorException' with message 'Illegal offset type in isset or empty' in /home/poolhero/poolhero/vendor/mcamara/laravel-localization/src/Mcamara/LaravelLocalization/LaravelLocalization.php:502
```
```
#0 vendor/mcamara/laravel-localization/src/Mcamara/LaravelLocalization/LaravelLocalization.php(502): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Illegal offset ...', '/home/...', 502, Array)
#1 vendor/mcamara/laravel-localization/src/Mcamara/LaravelLocalization/LaravelLocalization.php(216): Mcamara\LaravelLocalization\LaravelLocalization->checkLocaleInSupportedLocales(Array)
#2 …
```

Fix LanguageNegotiator Bug

---

src/Mcamara/LaravelLocalization/LaravelLocalization.php

Added a new **```getCurrentLocaleNative```** function, there are times when you want to display the current locale in the user's native language.  If a user selects Deutsch (German) in a drop down menu to charge their language to german, once the locale has been set and changed the site's language displays everything in German but the **```getCurrentLocaleName```** displays the word German not Deutsch.  So in cases like this use **```getCurrentLocaleNative```** instead of **```getCurrentLocaleName```** would be ideal.

Added a new getCurrentLocaleNative function

---

.travis.yml

Travis can test against PHP 7.0
The test scripts do not need `sudo`, so we can use the newer/faster test servers.

Travis - test PHP 7.0, use faster containers

---

src/Mcamara/LaravelLocalization/Middleware/LocaleSessionRedirect.php

When a localization has been removed from the system, leaving end-user in a broken cookie session.

Fix Issue #255 when a localization is removed

---

src/Mcamara/LaravelLocalization/Middleware/LocaleCookieRedirect.php
src/Mcamara/LaravelLocalization/Middleware/LocaleSessionRedirect.php

Fix the Problem where the locale was overwritten.
Already discussed in https://github.com/mcamara/laravel-localization/issues/281
This was already fixed in version 1.0 (https://github.com/mcamara/laravel-localization/pull/286).

fix if condition to not overwrite $locale

---

src/Mcamara/LaravelLocalization/LaravelLocalizationServiceProvider.php

When using constructor injection with the class name, each time a new instance is created.
With this change, the service provider registers itself using the full class name. This makes sure the same instance is used each time.
Also added an alias to keep backwards-compatibility.

Change the way the ServiceProvider registers the class

---

composer.json
src/Mcamara/LaravelLocalization/LaravelLocalization.php
tests/LocalizerTests.php

In Laravel 5.4 the `trans` method of the `Translator` [class](https://laravel.com/api/5.4/Illuminate/Translation/Translator.html#method_trans) accepts 3 arguments instead of 4, therefore the `getURLFromRouteNameTranslated` method of the package is no longer able to translate current routes.
Also pre L5.4 tests require the `testbench-browser-kit` package, as stated in the [upgrade guide](https://laravel.com/docs/5.4/upgrade).

Fix route translation for Laravel 5.4

---

README.md
src/Mcamara/LaravelLocalization/LaravelLocalization.php
src/config/config.php

Added another field in the configuration file so the language order can be specified.
Basically we define the order we want in the 'localesOrder' field.
Example `'localesOrder' => ['es','en']`
Then in the blade file we output the language selector we call 
```
<ul class="language_bar_chooser">
@foreach(LaravelLocalization::getLocalesOrder() as $localeCode => $properties)
<li>
<a rel="alternate" hreflang="{{$localeCode}}" href="{{LaravelLocalization::getLocalizedURL($localeCode) }}">
{{ $properties['native'] }}
</a>
</li>
@endforeach
</ul>
```
and then the languages will have the order we specified. Don't forget to run `php artisan config:cache` after a config change

Added support for custom order

---

.travis.yml
composer.json

Remove the version hint as suggested in
https://getcomposer.org/doc/04-schema.md#version
Any version or revision should be determined by a tag, branch or commit SHA.
TravisCI:
Remove --dev flag as it's no longer honored.
Prefer dist over original sources for deps on Travis (performance).

Tweak PHP Composer settings

---

src/Mcamara/LaravelLocalization/LaravelLocalization.php
tests/LocalizerTests.php

Related to https://github.com/mcamara/laravel-localization/issues/293
Fo fix the issue e.g. when you need to draw menu to change language but hideDefaultLocaleInURL set to TRUE and you can't switch to this default language.
```
<li class="dropdown">
<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Languahe <span class="caret"></span></a>
<ul class="dropdown-menu">
@foreach(LaravelLocalization::getSupportedLocales() as $localeCode => $properties)
<li>
<a rel="alternate" hreflang="{{ $localeCode }}" href="{{ LaravelLocalization::getLocalizedURL($localeCode, null, [], true) }}">
{{ $properties['native'] }}
</a>
</li>
@endforeach
</ul>
</li>
```
Here default language will be forced in the URL with …

[#293] Cant switch to default language if hiding default locale in URL

---

README.md
src/Mcamara/LaravelLocalization/Middleware/LaravelLocalizationViewPath.php

Added a new middleware to dynamically add current locale-code as view-path-root.

Added new middleware to dynamically use current locale as base-view-path

---

composer.json

Currently configuration fails with Laravel 5.4.*.

Authorize Laravel 5.3 and 5.4

---

README.md
src/Mcamara/LaravelLocalization/LaravelLocalization.php
tests/LocalizerTests.php

Some users might want to have the list of supported language excluding the one which is selected at the moment.
```
{{ LaravelLocalization::getSupportedLocales(true) }}
```
enables to exclude it via `$excludeCurrent` param.

Exclude current locale from the language selector

---

composer.json

Unlocking Laravel 5.6 doesn't seem to break anything.

support Laravel 5.6

---

src/Mcamara/LaravelLocalization/LaravelLocalization.php

Fix #468 and #429 
When app is running in the console, we should use the default value of config('app.locale'), don't need to negotiator with the accept-language

Fix #468 and #429

---

README.md
src/Mcamara/LaravelLocalization/LaravelLocalization.php

@mcamara, @lotestudio this update is server configuration specific:
- some linux installations suffix locales with ".UTF-8", some with ".utf8"
- on Windows there is no suffix
I'd propose to remove the forced suffix from setLocale and put suggestion in docs that this need's to be set on a development env in config file.
Optionally a setting 'utf8suffix' => env('LARAVELLOCALIZATION_UTF8SUFFIX', '.UTF-8') could be introduced in config file in order to be able to set this per local environment.

remove UTF-8 suffix from regional

---

CACHING.md
CHANGELOG.md
README.md
phpunit.xml.dist
src/Mcamara/LaravelLocalization/Commands/RouteTranslationsCacheCommand.php
src/Mcamara/LaravelLocalization/Commands/RouteTranslationsClearCommand.php
src/Mcamara/LaravelLocalization/Commands/RouteTranslationsListCommand.php
src/Mcamara/LaravelLocalization/LaravelLocalization.php
src/Mcamara/LaravelLocalization/LaravelLocalizationServiceProvider.php
src/Mcamara/LaravelLocalization/Traits/LoadsTranslatedCachedRoutes.php
src/Mcamara/LaravelLocalization/Traits/TranslatedRouteCommandContext.php
src/stubs/routes.stub

Here's my take on what we discussed by email earlier. This merges in only the existing functionality offered by [czim/laravel-localization-route-cache](https://github.com/czim/laravel-localization-route-cache), nothing else.
The changes should be backwards-compatible, and only require changes to the setup for people who already make use of route caching, or the old separate caching package.
I tried to match style and keep things clean. If you want me to tweak the style further, let me know what needs to change and I'll take care of it.
I did not add tests. I think I'd have to set up orchestra testbench as a dev composer dependency and do a whole bunch of work to get those rolling. It'd be worth it, but I wanted to present this first, and check how you feel about tests for this package -- …

Merge in logic of czim/laravel-localization-route-cache

---

src/Mcamara/LaravelLocalization/Middleware/LaravelLocalizationMiddlewareBase.php
src/config/config.php
tests/LocalizerTests.php
tests/full-config/config.php

This PR adds a new configuration setting `urlsIgnored`, where developer can specify URLs to skip.

Load skipped URLs from configuration.

---

composer.json

this **PR** removes useless **||** requires , as[ composer tilde version range](https://getcomposer.org/doc/articles/versions.md#tilde-version-range-) will work

Remove useless required from composer

---

src/Mcamara/LaravelLocalization/Middleware/LaravelLocalizationRedirectFilter.php

The `elseif` is superfluous. Note that
`
($currentLocale !== $defaultLocale || !$hideDefaultLocale)`
is equivalent to
`!(($currentLocale == $defaultLocale && $hideDefaultLocale))`
This means the `elseif` part is only executed if the locale from url is not valid and 
`
!(($currentLocale == $defaultLocale && $hideDefaultLocale))`
but this case has been checked before in `LocaleSessionRedirect`. If the middleware  `LocaleSessionRedirect` is not used, then `session(‘locale’)` is null anyway and `$redirection` remains false. 
Thus its also superfluous to check `if($redirection)` since there is only one case. There is also no need for some variables since they occur now only once. The variable `!empty($locales[$localeCode])` can be replaced by …

Cleanup code in LaravelLocalizationRedirectFilter

---

README.md
src/Mcamara/LaravelLocalization/LanguageNegotiator.php
src/config/config.php

Hi there,
this is my first pull request ever, so there may be mistakes and errors in the workflow, which I would kindly ask you to tell me about in order to fix that.
Here is my goal:
On a client project I have been asked to introduce custom lang prefixes in the supported locales like "uk" instead of "en-GB". So I changed the corresponding key in the config/laravellocalization.php, but of course this led to issues as the automatic language negotiator based on the browser language couldn't match it.
So I enhanced the config/laravellocalizaton.php and added some custom localesMapping array, in which you could specify the desired mapping like this:
`
'localesMapping' => [
'en-GB' => 'uk',
'de-AT' => 'at',
]
`
To use this mapping I changed the LanguageNegotiator class and added a call to the …

Mapping locales to custom prefixes

---

README.md
src/Mcamara/LaravelLocalization/LaravelLocalization.php
src/Mcamara/LaravelLocalization/Middleware/LaravelLocalizationRedirectFilter.php
src/Mcamara/LaravelLocalization/Middleware/LocaleCookieRedirect.php
src/Mcamara/LaravelLocalization/Middleware/LocaleSessionRedirect.php

This commits fixes https://github.com/mcamara/laravel-localization/issues/305
If one enables `useAcceptLanguageHeader` and `hideDefaultLocaleInURL` then this works now. If the first request contains no local in the url, the local will be determined by the AcceptLanguageHeader and stored in the session. While the session is active, AcceptLanguageHeader will not be used again. Instead, if the url contains no locale, then default locale will be shown.
Also this commits includes a fix for https://github.com/mcamara/laravel-localization/pull/598 I apologize that I missed one case when testing. When `hideDefaultLocaleInURL` is disabled and one calls a url without locale, then no redirect was happening. This is because I missed in my argumentation in …

Fix https://github.com/mcamara/laravel-localization/issues/305

---

src/Mcamara/LaravelLocalization/LaravelLocalization.php
tests/LocalizerTests.php

Fixed getLocalizedURL producing duplicate query string (side effect of #578). The test is included.

getLocalizedURL produce duplicate query string

---

CHANGELOG.md
README.md
src/Mcamara/LaravelLocalization/LaravelLocalization.php
tests/LocalizerTests.php

```php
app('config')->set('laravellocalization.localesMapping', [
'en' => 'custom',
]);
// Route::prefix(app(...)->setLocale()) => http://localhost/cusom => custom
$this->assertEquals('custom', app('laravellocalization')->setLocale('custom'));
// Current locale is en
$this->assertEquals('en', app('laravellocalization')->getCurrentLocale());
// both are in supported locales
$this->assertTrue(app('laravellocalization')->checkLocaleInSupportedLocales('en'));
$this->assertTrue(app('laravellocalization')->checkLocaleInSupportedLocales('custom'));
// use the mapping
$this->assertEquals('http://localhost/custom/some-route', app('laravellocalization')->localizeURL('some-route', 'en'));
$this->assertEquals('http://localhost/custom/some-route', app('laravellocalization')->localizeURL('some-route', …
```

Respect locales mapping

---

src/Mcamara/LaravelLocalization/Commands/RouteTranslationsCacheCommand.php
src/Mcamara/LaravelLocalization/Commands/RouteTranslationsListCommand.php
src/Mcamara/LaravelLocalization/Traits/LoadsTranslatedCachedRoutes.php

- The list command works again in Laravel 5.8. Also, running applications in console now respects the current locale when routes are cached.
- The cache command is cleaned up.
Fixes #638.

Fixed issues with translated route caching

---

src/Mcamara/LaravelLocalization/LaravelLocalization.php
src/Mcamara/LaravelLocalization/Traits/LoadsTranslatedCachedRoutes.php

A previous commit for caching (PR #651 . See line 175 in vendor/mcamara/laravel-localization/src/LaravelLocalization.) broke the functionality of `hideDefaultLocale`
(with and without cache).
The purpose of `setLocale` is to return the locale of the url (even if there is none).
This is necessary for ensuring that the current requested route actually exists.
Therefore this behavior was reestablished.
The file `bootstrap/cache/routes_**.php` imitates the routes that
are otherwise generated by the `setLocale` group in `routes/web.php`. 
Therefore, its essential that `**` has the value of the locale of the url 
(which is `setLocale`).
A nullable locale must refer to `bootstrap/cache/routes.php`.
Fixes #656
Fixes #661

Fix hideDefaultLocale

---

tests/LocalizerTests.php

A recent change in `setLocale` caused that `hideDefaultLocaleInURL`
is causing a `404` error when an uri with default locale is accessed.
A test for this scenario has been created, but it currently fails
in release 1.4.2.
See #656 for more

Add test to check independece of getLocale and hideDefaultLocale

---

README.md
src/config/config.php

Many issues show that it is difficult to understand
how `hideDefaultLocaleInURL` and `useAcceptLanguageHeader`
work, especially how the middleware will effect them
and if they are used in combination.
Also the description of hideDefaultLocaleInURL was outdated in
the config file.
This commit is an attempt to be more clear about these configuration
setup and the behaviour of the associated middleware.

 Improve config description and readme.md

---

README.md

The issue that a POST is not working, seems to
came up very offten in the issue section.
Therefore this commit integrates that into the
readme.md
I also replaced `getLocalizedURL` with `localizeURL`
because its shorter, and I think most people
just want to pass the `url` anyway.

Add common issues to read.me

---

README.md
src/Mcamara/LaravelLocalization/Middleware/LocaleCookieRedirect.php

Also made it compatible for the case that its used with hidden default locale and accept header.
Closes #613

Added LocaleCookieRedirect Middleware to Readme

---

src/Mcamara/LaravelLocalization/LaravelLocalization.php
tests/LocalizerTests.php

Hello there, first pull request for me on this project
I have a bug on production with your package.
I have an non-translated route where I use the middleware 'LocaleSessionRedirect'.
'LocaleSessionRedirect' uses the 'getLocalizedURL' method which produce an url with a duplicate query string.
In my opinion the query string should be removed from the variable '$url' even when is is empty to begin with
I added the tests along the patch. ( the test wasn't passing before the patch )

Fixed getLocalizedURL producing duplicate query string

---

ADDITIONS.md
README.md

This is a proposal how to change the structure of the readme to make it more readable for freshman (you may take a look at https://github.com/iwasherefirst2/laravel-localization/tree/changeReadmeALot).
I came up with this after closing a lot of issues and realizing there were 3 mayor problems
1. People did not know what this package offers and what not 
2. People were confused how and when to use middleware 
3. People did not localize POST urls.
Proposed changes:
- Add list of features that the package offers as a summary on top
- Move Collaborators to bottom for readability
- Move installation of outdated Laravel 5.4< on extra Additions.md page
- Move Config/Middleware setup into installation section
- Name 8 config settings in readme (when you look first time into the config file, you …

Make readme more readable for freshman

---

README.md
src/Mcamara/LaravelLocalization/Interfaces/LocalizedUrlRoutable.php
src/Mcamara/LaravelLocalization/LaravelLocalization.php
tests/LocalizerTests.php
tests/ModelWithTranslatableRoutes.php

To make route parameters translatable, a model is required to have multiple translated slugs (one for each language). There is no default way to add multiple slugs for one model, so users have to create this manually.
To add this functionality the user has to provide the package access to the slug of a model for every locale. For that purpose, the model should implement the new introduced `LocalizedUrlRoutable` interface. The interface comes with only one function `getLocalizedRouteKey($locale)` which returns the localized slug for the model. 
When a model has implemented the interface, the functions `localizeUrl`, `getLocalizedURL` or `getURLFromRouteNameTranslated` etc. will also translate the parameter.
For example, when the translated route in `en/routes.php` looks like this
[ 'page' …

Add translatable route parameters

---

README.md

It seems that the section for translatable urls were not self-explanatory enough. 
The latest issues were raised about this functionality, see #672, #681, #682
Improved examples, improved structure, and also added a tutorial video.

Improve translatable url section in readme

---

src/Mcamara/LaravelLocalization/LaravelLocalization.php

It conflicts with other `env()` global functions (such as CakePHP), and most of them don't handle closures.

Use Env::get instead of env

---

README.md

In `localizeUrl('(/test)')`, the `()` is redundant. It will generate wrong url like `https://host/en/(/test)`.

In `localizeUrl('(/test)')`, the `()` is redundant

---

src/Mcamara/LaravelLocalization/LaravelLocalization.php

This PR fixes the below warning when running on PHP 8.1:
```
parse_url(): Passing null to parameter #1 ($url) of type string is deprecated in .../vendor/mcamara/laravel-localization/src/Mcamara/LaravelLocalization/LaravelLocalization.php on line 273
```

fix: Passing null to parameter #1 in parse_url()

---

README.md

This appears to be the most direct way to make links within a website that leverage the `routes.php` files. The lack of documentation for the use of the attributes took me way to long to look up. So here I am providing a simple addition to the documentation to help others (and myself) in the future.

Add an example with attributes for getURLFromRouteNameTranslated

---

CHANGELOG.md
UPGRADING.md
src/Mcamara/LaravelLocalization/LaravelLocalization.php
src/Mcamara/LaravelLocalization/LaravelLocalizationServiceProvider.php
tests/LocalizerTests.php

Hi, this PR adds support for [contextual binding](https://laravel.com/docs/10.x/container#contextual-binding) in Laravel.
This comes in handy when you want to inject a different implementation into the `LaravelLocalization` class.
A quick example: We have extended Laravel's translations loader to support loading translations from the database.
We have done so by overwriting the `app('translator')` in the container.
However, to improve performance we would like to only load translations from the filesystem when using this package.
Before this PR, there was no way to tell Laravel that the `LaravelLocalization` class can only use the file loader.
After this PR, we can now tell Laravel to inject the file loader instance when it is requested by the `LaravelLocalization` class:
```php
$this …
```

Support contextual binding

---

src/config/config.php

Fix typos and missing carriage returns where describing 'localesMapping' feature.

Fix typos and layout in config.php

---

README.md

Removed the Gitter chat badge from the README, GitHub issues should be used instead.

docs: remove chat badge

---

README.md

Link was pointing to `#LaravelLocalizationRoutes` which doesn't exist anymore. This most likely was replaced with `#installation`.

Updated link to appropriate installation section

---

composer.json

Previous (unsupported) versions were kept in the composer.json file. These version constraints are now aligned with what is mentioned in the README and the run-tests action.

chore: update PHP and Laravel version requirements
