mcamara/laravel-localization

README.md

I added this helper to the readme, it is a fundamental value that most developers will have to access.

Readme addition: getCurrentLocale()

---

src/Mcamara/LaravelLocalization/LaravelLocalization.php

Decodes back previously parsed url so we can have match in routes translation file.

fixes #174

---

README.md

Specify where exactly to add the middleware

---

README.md

Fixing #182#issuecomment-97234244

Corrected middleware order in Readme.md

---

composer.json

Allow laravel 5.1
http://semver.mwl.be/#?package=laravel%2Flaravel&version=~5.0&minimum-stability=stable

Allow laravel 5.1

---

src/Mcamara/LaravelLocalization/Middleware/LocaleCookieRedirect.php
src/Mcamara/LaravelLocalization/Middleware/LocaleSessionRedirect.php

Think this issue is fixed now:
https://github.com/mcamara/laravel-localization/issues/219
$locale was undefined in the first if statement

Fix #219 - $locale was undefined

---

src/Mcamara/LaravelLocalization/Middleware/LocaleCookieRedirect.php
src/Mcamara/LaravelLocalization/Middleware/LocaleSessionRedirect.php

Please check this Pull-Request related to the open issue 
https://github.com/mcamara/laravel-localization/issues/281

bugfix - fix if conditions

---

src/Mcamara/LaravelLocalization/Middleware/LocaleCookieRedirect.php

Cookies are now set as they should. Please ignore the comments in my first commit. The second one is the one that contains the correct fix.

Fix: Cookies now work

---

src/config/config.php

use correct code for swedish

---

src/Mcamara/LaravelLocalization/LaravelLocalization.php

fix routes.translation event listen doesn't work https://github.com/mcamara/laravel-localization/issues/322

event listen add $locale parameter

---

src/Mcamara/LaravelLocalization/Middleware/LocaleCookieRedirect.php

(Fixing LocaleCookieRedirect.php)
Referencing commit: https://github.com/mcamara/laravel-localization/commit/b8b9f4e2dfc96b24dba715f1ea3213021f02ecfb

Fix Issue #255 when a localization is removed (for CookieRedirect)

---

src/Mcamara/LaravelLocalization/LaravelLocalization.php

See: https://github.com/mcamara/laravel-localization/issues/338

Add support for subdirectories as base url

---

src/Mcamara/LaravelLocalization/LanguageNegotiator.php

When testing the negotiateLanguage i found out that the browser never found a match, that was because this function was only checking the supportedLocales array keys.
for example, my locale key is "pt" but my browser was negociating "pt-PT".

Update on function negotiateLanguage

---

CHANGELOG.md
src/Mcamara/LaravelLocalization/LaravelLocalization.php
src/Mcamara/LaravelLocalization/LaravelLocalizationServiceProvider.php

Add compatibility with Laravel 5.4

---

README.md

Removing additional indent code blocks

---

README.md

Simplify installation process
* Use composer command instead of manual editing composer.json
* Remove *Manual* section

Simplify installation process

---

src/Mcamara/LaravelLocalization/Middleware/LaravelLocalizationViewPath.php

Fix namespace issue. Address issue #450

---

composer.json

Same as #464 which is inactive since more than 20 days

Add support for auto-discovery

---

README.md

adds syntax highlight to `resources/lang/language_abbreviation` for easier read.

adds syntax highlight to folder path

---

src/Mcamara/LaravelLocalization/Middleware/LaravelLocalizationRedirectFilter.php

Issue #546 - Fix issue with unable to detect routes properly when there are multiple consecutive slashes before locale.

Issue #546 - Fix issue with unable to detect routes properly when there are multiple consecutive slashes before locale.

---

src/Mcamara/LaravelLocalization/LanguageNegotiator.php
src/Mcamara/LaravelLocalization/LaravelLocalization.php
src/Mcamara/LaravelLocalization/LaravelLocalizationServiceProvider.php
src/Mcamara/LaravelLocalization/Middleware/LaravelLocalizationRedirectFilter.php
src/Mcamara/LaravelLocalization/Middleware/LaravelLocalizationRoutes.php
src/Mcamara/LaravelLocalization/Middleware/LaravelLocalizationViewPath.php
src/Mcamara/LaravelLocalization/Middleware/LocaleCookieRedirect.php
src/Mcamara/LaravelLocalization/Middleware/LocaleSessionRedirect.php

First, thank you for creating this package - found it very useful.
The cope of this PR includes:
- dropped unused imports (less auto-loading)
- enabled opcache codes (the functions prepended with a backslash, improves performance)
- applied null-coalescing operator where it does fit
- tweaked an if-condition (micro-optimization)
- the dropped field is exactly same as in parent class
Only minor things, didn't find anything more serious: great job!

Minor code tweaks found by Static Code Analysys

---

README.md

Hi @mcamara,
unfortunately I did miss a part of the documentation. So here it is.
Thank you,
Chris

Amend locales mapping readme

---

composer.json
tests/LocalizerTests.php
tests/full-config/config.php

Hi @mcamara,
sorry for opening pull requests again and again, but I'm still at the beginning and realized, that I should have added a test to proof that localesMapping is working. I just did that now.
Cheers,
Chris

locales mapping test

---

src/Mcamara/LaravelLocalization/LaravelLocalization.php

Hi, this package is very useful, thank you!
In relation to #432 , currently I use the following fix in my projects and there is a significant improvement in the performance. It is a simple cache functionality for the already translated routes in `findTranslatedRouteByUrl()`.

Translated routes by url caching

---

.travis.yml
README.md
composer.json

Tests failing because of: https://github.com/orchestral/testbench/issues/238
I will take a look at them later (help would be appreciated :) ) but I'd like to push compatibility to the new version of Laravel as soon as possible.

Updated to laravel 5.8

---

README.md

Code change not represented in readme:
https://github.com/mcamara/laravel-localization/issues/324

Fix Documentation redirect status

---

README.md

This allows proper syntax highlighting for the blade code example

Added blade type to code block in README

---

README.md

I followed the discussion [here](https://github.com/mcamara/laravel-localization/issues/161#issuecomment-526537412) with great interest, as I've bene thinking about using testing with this package for a while.
I'm happy with the solution @V35CH provided and think it would be a valuable addition to the docs.
Some questions for the maintainers:
- If the provided solution okay?
- Are you satisfied with the provided explanation in the readme? Happy to make changes when needed.

Readme: add testing fix + information

---

src/Mcamara/LaravelLocalization/Commands/RouteTranslationsCacheCommand.php
src/Mcamara/LaravelLocalization/Commands/RouteTranslationsListCommand.php
src/Mcamara/LaravelLocalization/LaravelLocalization.php
src/Mcamara/LaravelLocalization/Traits/LoadsTranslatedCachedRoutes.php

Fixes combination of cached routes and hide default locale in URL

---

src/Mcamara/LaravelLocalization/LaravelLocalization.php
tests/LocalizerTests.php

Also added a test case for this scenario.
Fixes #634

Maintain query string when hidedDefaultLocaleInURL is true

---

README.md

It says localeCookieRedirect middleware stores locale in session. I replace session with cookie.

fix LocaleCookieRedirect section

---

README.md

I think this method is really important and should not be missing in the helpers section.

Add a section for getCurrentLocaleNative()

---

README.md

Update misspell at README.md

---

README.md

Added void to tearDown() in docs
